// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cerc/onboarding/v1/query.proto

package onboarding

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParticipantsRequest queries participants
type QueryParticipantsRequest struct {
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryParticipantsRequest) Reset()         { *m = QueryParticipantsRequest{} }
func (m *QueryParticipantsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParticipantsRequest) ProtoMessage()    {}
func (*QueryParticipantsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80831d904221d27d, []int{0}
}
func (m *QueryParticipantsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParticipantsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParticipantsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParticipantsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParticipantsRequest.Merge(m, src)
}
func (m *QueryParticipantsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParticipantsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParticipantsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParticipantsRequest proto.InternalMessageInfo

func (m *QueryParticipantsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryParticipantsResponse is response type for querying the participants
type QueryParticipantsResponse struct {
	Participants []*Participant `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty" json:"participants" yaml:"participants"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryParticipantsResponse) Reset()         { *m = QueryParticipantsResponse{} }
func (m *QueryParticipantsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParticipantsResponse) ProtoMessage()    {}
func (*QueryParticipantsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80831d904221d27d, []int{1}
}
func (m *QueryParticipantsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParticipantsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParticipantsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParticipantsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParticipantsResponse.Merge(m, src)
}
func (m *QueryParticipantsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParticipantsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParticipantsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParticipantsResponse proto.InternalMessageInfo

func (m *QueryParticipantsResponse) GetParticipants() []*Participant {
	if m != nil {
		return m.Participants
	}
	return nil
}

func (m *QueryParticipantsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryGetParticipantByAddressRequest queries participant by the laconic
// address
type QueryGetParticipantByAddressRequest struct {
	// Laconic address
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryGetParticipantByAddressRequest) Reset()         { *m = QueryGetParticipantByAddressRequest{} }
func (m *QueryGetParticipantByAddressRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetParticipantByAddressRequest) ProtoMessage()    {}
func (*QueryGetParticipantByAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80831d904221d27d, []int{2}
}
func (m *QueryGetParticipantByAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetParticipantByAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetParticipantByAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetParticipantByAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetParticipantByAddressRequest.Merge(m, src)
}
func (m *QueryGetParticipantByAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetParticipantByAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetParticipantByAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetParticipantByAddressRequest proto.InternalMessageInfo

func (m *QueryGetParticipantByAddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryGetParticipantByAddressResponse is response type for querying
// participant by the laconic address
type QueryGetParticipantByAddressResponse struct {
	// Participant details
	Participant *Participant `protobuf:"bytes,1,opt,name=participant,proto3" json:"participant,omitempty"`
}

func (m *QueryGetParticipantByAddressResponse) Reset()         { *m = QueryGetParticipantByAddressResponse{} }
func (m *QueryGetParticipantByAddressResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetParticipantByAddressResponse) ProtoMessage()    {}
func (*QueryGetParticipantByAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80831d904221d27d, []int{3}
}
func (m *QueryGetParticipantByAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetParticipantByAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetParticipantByAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetParticipantByAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetParticipantByAddressResponse.Merge(m, src)
}
func (m *QueryGetParticipantByAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetParticipantByAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetParticipantByAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetParticipantByAddressResponse proto.InternalMessageInfo

func (m *QueryGetParticipantByAddressResponse) GetParticipant() *Participant {
	if m != nil {
		return m.Participant
	}
	return nil
}

// QueryGetParticipantByNitroAddressRequest queries participant by the nitro
// address
type QueryGetParticipantByNitroAddressRequest struct {
	// Nitro address
	NitroAddress string `protobuf:"bytes,1,opt,name=nitro_address,json=nitroAddress,proto3" json:"nitro_address,omitempty"`
}

func (m *QueryGetParticipantByNitroAddressRequest) Reset() {
	*m = QueryGetParticipantByNitroAddressRequest{}
}
func (m *QueryGetParticipantByNitroAddressRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetParticipantByNitroAddressRequest) ProtoMessage()    {}
func (*QueryGetParticipantByNitroAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80831d904221d27d, []int{4}
}
func (m *QueryGetParticipantByNitroAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetParticipantByNitroAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetParticipantByNitroAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetParticipantByNitroAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetParticipantByNitroAddressRequest.Merge(m, src)
}
func (m *QueryGetParticipantByNitroAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetParticipantByNitroAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetParticipantByNitroAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetParticipantByNitroAddressRequest proto.InternalMessageInfo

func (m *QueryGetParticipantByNitroAddressRequest) GetNitroAddress() string {
	if m != nil {
		return m.NitroAddress
	}
	return ""
}

// QueryGetParticipantByNitroAddressResponse is response type for querying
// participant by the nitro address
type QueryGetParticipantByNitroAddressResponse struct {
	// Participant details
	Participant *Participant `protobuf:"bytes,1,opt,name=participant,proto3" json:"participant,omitempty"`
}

func (m *QueryGetParticipantByNitroAddressResponse) Reset() {
	*m = QueryGetParticipantByNitroAddressResponse{}
}
func (m *QueryGetParticipantByNitroAddressResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryGetParticipantByNitroAddressResponse) ProtoMessage() {}
func (*QueryGetParticipantByNitroAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80831d904221d27d, []int{5}
}
func (m *QueryGetParticipantByNitroAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetParticipantByNitroAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetParticipantByNitroAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetParticipantByNitroAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetParticipantByNitroAddressResponse.Merge(m, src)
}
func (m *QueryGetParticipantByNitroAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetParticipantByNitroAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetParticipantByNitroAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetParticipantByNitroAddressResponse proto.InternalMessageInfo

func (m *QueryGetParticipantByNitroAddressResponse) GetParticipant() *Participant {
	if m != nil {
		return m.Participant
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParticipantsRequest)(nil), "cerc.onboarding.v1.QueryParticipantsRequest")
	proto.RegisterType((*QueryParticipantsResponse)(nil), "cerc.onboarding.v1.QueryParticipantsResponse")
	proto.RegisterType((*QueryGetParticipantByAddressRequest)(nil), "cerc.onboarding.v1.QueryGetParticipantByAddressRequest")
	proto.RegisterType((*QueryGetParticipantByAddressResponse)(nil), "cerc.onboarding.v1.QueryGetParticipantByAddressResponse")
	proto.RegisterType((*QueryGetParticipantByNitroAddressRequest)(nil), "cerc.onboarding.v1.QueryGetParticipantByNitroAddressRequest")
	proto.RegisterType((*QueryGetParticipantByNitroAddressResponse)(nil), "cerc.onboarding.v1.QueryGetParticipantByNitroAddressResponse")
}

func init() { proto.RegisterFile("cerc/onboarding/v1/query.proto", fileDescriptor_80831d904221d27d) }

var fileDescriptor_80831d904221d27d = []byte{
	// 542 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcb, 0x6e, 0xd3, 0x4c,
	0x18, 0xcd, 0xf4, 0xff, 0x01, 0x31, 0x09, 0x9b, 0x11, 0x12, 0x21, 0xaa, 0xdc, 0xc8, 0x41, 0xd4,
	0x94, 0x66, 0x46, 0x09, 0x0b, 0xee, 0x42, 0xc9, 0x82, 0xee, 0xa0, 0x78, 0xc9, 0x06, 0x8d, 0xed,
	0x91, 0x35, 0x28, 0x9d, 0x71, 0x3d, 0xd3, 0x88, 0xa8, 0xea, 0x86, 0x27, 0x40, 0x42, 0xbc, 0x0f,
	0x12, 0x1b, 0x96, 0x95, 0x90, 0x10, 0xab, 0x0a, 0x25, 0x3c, 0x01, 0x4f, 0x80, 0x3c, 0x36, 0x74,
	0x5c, 0x9c, 0x0b, 0x88, 0x9d, 0xfd, 0xdd, 0xce, 0x39, 0xdf, 0x77, 0x6c, 0xe8, 0x84, 0x2c, 0x0d,
	0x89, 0x14, 0x81, 0xa4, 0x69, 0xc4, 0x45, 0x4c, 0xc6, 0x3d, 0xb2, 0x7f, 0xc0, 0xd2, 0x09, 0x4e,
	0x52, 0xa9, 0x25, 0x42, 0x59, 0x1e, 0x9f, 0xe6, 0xf1, 0xb8, 0xd7, 0xba, 0x1c, 0xcb, 0x58, 0x9a,
	0x34, 0xc9, 0x9e, 0xf2, 0xca, 0xd6, 0x56, 0x28, 0xd5, 0x9e, 0x54, 0x24, 0xa0, 0x8a, 0xe5, 0x23,
	0xc8, 0xb8, 0x17, 0x30, 0x4d, 0x7b, 0x24, 0xa1, 0x31, 0x17, 0x54, 0x73, 0x29, 0x8a, 0xda, 0x4e,
	0x05, 0xaa, 0x85, 0x91, 0x17, 0xad, 0xc7, 0x52, 0xc6, 0x23, 0x46, 0x68, 0xc2, 0x09, 0x15, 0x42,
	0x6a, 0x33, 0x41, 0xe5, 0x59, 0x37, 0x80, 0xcd, 0x67, 0x19, 0xc8, 0x2e, 0x4d, 0x35, 0x0f, 0x79,
	0x42, 0x85, 0x56, 0x3e, 0xdb, 0x3f, 0x60, 0x4a, 0xa3, 0xc7, 0x10, 0x9e, 0x42, 0x36, 0x41, 0x1b,
	0x78, 0xf5, 0xfe, 0x75, 0x9c, 0xf3, 0xc3, 0x19, 0x3f, 0x9c, 0x4b, 0x2c, 0xf8, 0xe1, 0x5d, 0x1a,
	0xb3, 0xa2, 0xd7, 0xb7, 0x3a, 0xdd, 0xcf, 0x00, 0x5e, 0xad, 0x00, 0x51, 0x89, 0x14, 0x8a, 0xa1,
	0x04, 0x36, 0x12, 0x2b, 0xde, 0x04, 0xed, 0xff, 0xbc, 0x7a, 0x7f, 0x03, 0xff, 0xbe, 0x31, 0x6c,
	0xf5, 0x0f, 0x6f, 0x7e, 0x3f, 0xd9, 0xd8, 0x7c, 0xa9, 0xa4, 0xb8, 0xe7, 0xda, 0xed, 0x6e, 0x7b,
	0x42, 0xf7, 0x46, 0x67, 0x62, 0x7e, 0x09, 0x01, 0xed, 0x94, 0x74, 0xad, 0x19, 0x5d, 0x9b, 0x4b,
	0x75, 0xe5, 0x74, 0x4b, 0xc2, 0x1e, 0xc1, 0x8e, 0xd1, 0xb5, 0xc3, 0xb4, 0x4d, 0x6d, 0x32, 0x88,
	0xa2, 0x94, 0xa9, 0x5f, 0x7b, 0x6c, 0xc2, 0x0b, 0x34, 0x8f, 0x98, 0x25, 0x5e, 0xf4, 0x7f, 0xbe,
	0xba, 0x1c, 0x5e, 0x5b, 0x3c, 0xa0, 0xd8, 0xd1, 0x00, 0xd6, 0x2d, 0x05, 0xc5, 0x29, 0x96, 0xad,
	0xc8, 0xb7, 0x7b, 0xdc, 0xa7, 0xd0, 0xab, 0x84, 0x7a, 0xc2, 0x75, 0x2a, 0xcf, 0x10, 0xee, 0xc0,
	0x4b, 0x22, 0x0b, 0xbf, 0x28, 0xd3, 0x6e, 0x08, 0xab, 0xd6, 0x15, 0xf0, 0xc6, 0x0a, 0x03, 0xff,
	0x99, 0x80, 0xfe, 0x87, 0xff, 0xe1, 0x39, 0x03, 0x88, 0xde, 0x01, 0xd8, 0xb0, 0xad, 0x84, 0xb6,
	0xab, 0x06, 0xcd, 0xb3, 0x75, 0xab, 0xbb, 0x62, 0x75, 0x4e, 0xdd, 0xf5, 0x5e, 0x7f, 0xfa, 0xf6,
	0x76, 0xcd, 0x45, 0x6d, 0x52, 0xf1, 0xb5, 0x95, 0x7c, 0xf5, 0x1e, 0xc0, 0x2b, 0x73, 0x2e, 0x89,
	0x6e, 0xcf, 0x05, 0x5d, 0x6c, 0x9e, 0xd6, 0x9d, 0x3f, 0x6f, 0x2c, 0x88, 0xf7, 0x0d, 0xf1, 0x6d,
	0xb4, 0xb5, 0x8c, 0x38, 0x39, 0x2c, 0xee, 0x7c, 0x84, 0x4e, 0x00, 0x5c, 0x5f, 0x74, 0x50, 0xf4,
	0x60, 0x65, 0x3a, 0x15, 0xc6, 0x6a, 0x3d, 0xfc, 0xcb, 0xee, 0x42, 0xd1, 0xc0, 0x28, 0xba, 0x8f,
	0xee, 0x2e, 0x53, 0xd4, 0x0d, 0x26, 0x5d, 0x63, 0x56, 0x72, 0x58, 0x32, 0xf2, 0xd1, 0x70, 0xf8,
	0x71, 0xea, 0x80, 0xe3, 0xa9, 0x03, 0xbe, 0x4e, 0x1d, 0xf0, 0x66, 0xe6, 0xd4, 0x8e, 0x67, 0x4e,
	0xed, 0xcb, 0xcc, 0xa9, 0x3d, 0xf7, 0x62, 0xae, 0xf1, 0x38, 0x0a, 0xb0, 0x96, 0x66, 0x7c, 0x97,
	0x4b, 0x32, 0xa2, 0xa1, 0x14, 0x3c, 0x8c, 0xc8, 0x2b, 0x0b, 0x2c, 0x38, 0x6f, 0x7e, 0x9d, 0xb7,
	0x7e, 0x04, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x10, 0xfa, 0xab, 0xf5, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Participants queries Participants list
	Participants(ctx context.Context, in *QueryParticipantsRequest, opts ...grpc.CallOption) (*QueryParticipantsResponse, error)
	// GetParticipantByAddress queries a participant by cosmos (laconic) address
	GetParticipantByAddress(ctx context.Context, in *QueryGetParticipantByAddressRequest, opts ...grpc.CallOption) (*QueryGetParticipantByAddressResponse, error)
	// GetParticipantByNitroAddress queries a participant by nitro address
	GetParticipantByNitroAddress(ctx context.Context, in *QueryGetParticipantByNitroAddressRequest, opts ...grpc.CallOption) (*QueryGetParticipantByNitroAddressResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Participants(ctx context.Context, in *QueryParticipantsRequest, opts ...grpc.CallOption) (*QueryParticipantsResponse, error) {
	out := new(QueryParticipantsResponse)
	err := c.cc.Invoke(ctx, "/cerc.onboarding.v1.Query/Participants", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetParticipantByAddress(ctx context.Context, in *QueryGetParticipantByAddressRequest, opts ...grpc.CallOption) (*QueryGetParticipantByAddressResponse, error) {
	out := new(QueryGetParticipantByAddressResponse)
	err := c.cc.Invoke(ctx, "/cerc.onboarding.v1.Query/GetParticipantByAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetParticipantByNitroAddress(ctx context.Context, in *QueryGetParticipantByNitroAddressRequest, opts ...grpc.CallOption) (*QueryGetParticipantByNitroAddressResponse, error) {
	out := new(QueryGetParticipantByNitroAddressResponse)
	err := c.cc.Invoke(ctx, "/cerc.onboarding.v1.Query/GetParticipantByNitroAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Participants queries Participants list
	Participants(context.Context, *QueryParticipantsRequest) (*QueryParticipantsResponse, error)
	// GetParticipantByAddress queries a participant by cosmos (laconic) address
	GetParticipantByAddress(context.Context, *QueryGetParticipantByAddressRequest) (*QueryGetParticipantByAddressResponse, error)
	// GetParticipantByNitroAddress queries a participant by nitro address
	GetParticipantByNitroAddress(context.Context, *QueryGetParticipantByNitroAddressRequest) (*QueryGetParticipantByNitroAddressResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Participants(ctx context.Context, req *QueryParticipantsRequest) (*QueryParticipantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Participants not implemented")
}
func (*UnimplementedQueryServer) GetParticipantByAddress(ctx context.Context, req *QueryGetParticipantByAddressRequest) (*QueryGetParticipantByAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParticipantByAddress not implemented")
}
func (*UnimplementedQueryServer) GetParticipantByNitroAddress(ctx context.Context, req *QueryGetParticipantByNitroAddressRequest) (*QueryGetParticipantByNitroAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParticipantByNitroAddress not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Participants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Participants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerc.onboarding.v1.Query/Participants",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Participants(ctx, req.(*QueryParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetParticipantByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetParticipantByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetParticipantByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerc.onboarding.v1.Query/GetParticipantByAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetParticipantByAddress(ctx, req.(*QueryGetParticipantByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetParticipantByNitroAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetParticipantByNitroAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetParticipantByNitroAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerc.onboarding.v1.Query/GetParticipantByNitroAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetParticipantByNitroAddress(ctx, req.(*QueryGetParticipantByNitroAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cerc.onboarding.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Participants",
			Handler:    _Query_Participants_Handler,
		},
		{
			MethodName: "GetParticipantByAddress",
			Handler:    _Query_GetParticipantByAddress_Handler,
		},
		{
			MethodName: "GetParticipantByNitroAddress",
			Handler:    _Query_GetParticipantByNitroAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cerc/onboarding/v1/query.proto",
}

func (m *QueryParticipantsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParticipantsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParticipantsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryParticipantsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParticipantsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParticipantsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Participants) > 0 {
		for iNdEx := len(m.Participants) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Participants[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetParticipantByAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetParticipantByAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetParticipantByAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetParticipantByAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetParticipantByAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetParticipantByAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Participant != nil {
		{
			size, err := m.Participant.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetParticipantByNitroAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetParticipantByNitroAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetParticipantByNitroAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NitroAddress) > 0 {
		i -= len(m.NitroAddress)
		copy(dAtA[i:], m.NitroAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.NitroAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetParticipantByNitroAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetParticipantByNitroAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetParticipantByNitroAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Participant != nil {
		{
			size, err := m.Participant.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParticipantsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryParticipantsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Participants) > 0 {
		for _, e := range m.Participants {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetParticipantByAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetParticipantByAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Participant != nil {
		l = m.Participant.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetParticipantByNitroAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NitroAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetParticipantByNitroAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Participant != nil {
		l = m.Participant.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParticipantsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParticipantsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParticipantsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParticipantsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParticipantsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParticipantsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participants", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Participants = append(m.Participants, &Participant{})
			if err := m.Participants[len(m.Participants)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetParticipantByAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetParticipantByAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetParticipantByAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetParticipantByAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetParticipantByAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetParticipantByAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participant", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Participant == nil {
				m.Participant = &Participant{}
			}
			if err := m.Participant.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetParticipantByNitroAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetParticipantByNitroAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetParticipantByNitroAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NitroAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NitroAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetParticipantByNitroAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetParticipantByNitroAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetParticipantByNitroAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participant", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Participant == nil {
				m.Participant = &Participant{}
			}
			if err := m.Participant.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
