// Generated by '@import-meta-env/typescript'

interface ImportMetaEnv {
  readonly REACT_APP_WALLET_CONNECT_PROJECT_ID: string;
  readonly REACT_APP_DEFAULT_GAS_PRICE: string;
  readonly REACT_APP_GAS_ADJUSTMENT: string;
  readonly REACT_APP_LACONICD_RPC_URL: string;
  readonly REACT_APP_ALLOWED_URLS: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
