// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cerc/nitro/v1/nitro.proto

package v1

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters of the nitro module.
type Params struct {
	NitroAdjudicatorAddress  []byte `protobuf:"bytes,1,opt,name=nitro_adjudicator_address,json=nitroAdjudicatorAddress,proto3" json:"nitro_adjudicator_address,omitempty"`
	VirtualPaymentAppAddress []byte `protobuf:"bytes,2,opt,name=virtual_payment_app_address,json=virtualPaymentAppAddress,proto3" json:"virtual_payment_app_address,omitempty"`
	ConsensusAppAddress      []byte `protobuf:"bytes,3,opt,name=consensus_app_address,json=consensusAppAddress,proto3" json:"consensus_app_address,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_049df55f6ca5af66, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetNitroAdjudicatorAddress() []byte {
	if m != nil {
		return m.NitroAdjudicatorAddress
	}
	return nil
}

func (m *Params) GetVirtualPaymentAppAddress() []byte {
	if m != nil {
		return m.VirtualPaymentAppAddress
	}
	return nil
}

func (m *Params) GetConsensusAppAddress() []byte {
	if m != nil {
		return m.ConsensusAppAddress
	}
	return nil
}

type PaymentChannel struct {
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (m *PaymentChannel) Reset()         { *m = PaymentChannel{} }
func (m *PaymentChannel) String() string { return proto.CompactTextString(m) }
func (*PaymentChannel) ProtoMessage()    {}
func (*PaymentChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_049df55f6ca5af66, []int{1}
}
func (m *PaymentChannel) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PaymentChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PaymentChannel.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PaymentChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentChannel.Merge(m, src)
}
func (m *PaymentChannel) XXX_Size() int {
	return m.Size()
}
func (m *PaymentChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentChannel.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentChannel proto.InternalMessageInfo

func (m *PaymentChannel) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

type Fund struct {
	TokenAddress string                `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Amount       cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
}

func (m *Fund) Reset()         { *m = Fund{} }
func (m *Fund) String() string { return proto.CompactTextString(m) }
func (*Fund) ProtoMessage()    {}
func (*Fund) Descriptor() ([]byte, []int) {
	return fileDescriptor_049df55f6ca5af66, []int{2}
}
func (m *Fund) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Fund) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Fund.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Fund) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fund.Merge(m, src)
}
func (m *Fund) XXX_Size() int {
	return m.Size()
}
func (m *Fund) XXX_DiscardUnknown() {
	xxx_messageInfo_Fund.DiscardUnknown(m)
}

var xxx_messageInfo_Fund proto.InternalMessageInfo

func (m *Fund) GetTokenAddress() string {
	if m != nil {
		return m.TokenAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "cerc.nitro.v1.Params")
	proto.RegisterType((*PaymentChannel)(nil), "cerc.nitro.v1.PaymentChannel")
	proto.RegisterType((*Fund)(nil), "cerc.nitro.v1.Fund")
}

func init() { proto.RegisterFile("cerc/nitro/v1/nitro.proto", fileDescriptor_049df55f6ca5af66) }

var fileDescriptor_049df55f6ca5af66 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xc1, 0x6e, 0xd3, 0x30,
	0x18, 0xc7, 0x13, 0x98, 0x2a, 0xc5, 0xda, 0x38, 0x04, 0xa6, 0xad, 0x03, 0x52, 0x54, 0x2e, 0x48,
	0xb0, 0x58, 0x85, 0xdb, 0x24, 0x0e, 0xdd, 0xa4, 0x49, 0xbd, 0x4d, 0x39, 0x72, 0x89, 0x3c, 0xdb,
	0xca, 0xcc, 0x12, 0x7f, 0x96, 0xed, 0x44, 0xec, 0x2d, 0x78, 0x04, 0x1e, 0x02, 0x89, 0x57, 0xe8,
	0xb1, 0xe2, 0x84, 0x38, 0x54, 0xa8, 0xbd, 0xf0, 0x18, 0x53, 0x6c, 0xb7, 0x55, 0x6f, 0x9f, 0xff,
	0xff, 0xff, 0xcf, 0xf9, 0xf2, 0x7d, 0x46, 0x43, 0xca, 0x35, 0xc5, 0x52, 0x58, 0x0d, 0xb8, 0x9b,
	0xf8, 0x22, 0x57, 0x1a, 0x2c, 0xa4, 0x47, 0xbd, 0x95, 0x7b, 0xa5, 0x9b, 0x9c, 0xbd, 0xaa, 0x00,
	0xaa, 0x9a, 0x63, 0xa2, 0x04, 0x26, 0x52, 0x82, 0x25, 0x56, 0x80, 0x34, 0x3e, 0x7c, 0x76, 0x42,
	0xc1, 0x34, 0x60, 0x70, 0x63, 0xaa, 0xfe, 0x9e, 0xc6, 0x54, 0xc1, 0x18, 0x7a, 0xa3, 0x74, 0x27,
	0xec, 0x0f, 0xc1, 0x7a, 0x51, 0x41, 0x05, 0x5e, 0xef, 0x2b, 0xaf, 0x8e, 0x7f, 0xc5, 0x68, 0x70,
	0x43, 0x34, 0x69, 0x4c, 0x7a, 0x81, 0x86, 0xee, 0xf3, 0x25, 0x61, 0x5f, 0x5b, 0x26, 0x28, 0xb1,
	0xa0, 0x4b, 0xc2, 0x98, 0xe6, 0xc6, 0x9c, 0xc6, 0x6f, 0xe2, 0x77, 0x87, 0xc5, 0x89, 0x0b, 0x4c,
	0x77, 0xfe, 0xd4, 0xdb, 0xe9, 0x67, 0xf4, 0xb2, 0x13, 0xda, 0xb6, 0xa4, 0x2e, 0x15, 0x79, 0x68,
	0xb8, 0xb4, 0x25, 0x51, 0x6a, 0x4b, 0x3f, 0x71, 0xf4, 0x69, 0x88, 0xdc, 0xf8, 0xc4, 0x54, 0xa9,
	0x0d, 0xfe, 0x11, 0x1d, 0x53, 0x90, 0x86, 0x4b, 0xd3, 0x9a, 0x3d, 0xf0, 0xa9, 0x03, 0x9f, 0x6f,
	0xcd, 0x1d, 0x33, 0xc6, 0xe8, 0x59, 0xb8, 0xe8, 0xea, 0x8e, 0x48, 0xc9, 0xeb, 0xf4, 0x35, 0x42,
	0xd4, 0x97, 0xa5, 0x60, 0xae, 0xe3, 0xa4, 0x48, 0x82, 0x32, 0x63, 0xe3, 0x0e, 0x1d, 0x5c, 0xb7,
	0x92, 0xa5, 0x6f, 0xd1, 0x91, 0x85, 0x7b, 0x2e, 0xf7, 0xfe, 0x2d, 0x29, 0x0e, 0x9d, 0xb8, 0xe9,
	0xe8, 0x0a, 0x0d, 0x48, 0x03, 0xad, 0xb4, 0xae, 0xf7, 0xe4, 0xf2, 0xfd, 0x7c, 0x39, 0x8a, 0xfe,
	0x2e, 0x47, 0xc7, 0x7e, 0xa6, 0x86, 0xdd, 0xe7, 0x02, 0x70, 0x43, 0xec, 0x5d, 0x3e, 0x93, 0xf6,
	0xf7, 0xcf, 0x73, 0x14, 0x86, 0x3d, 0x93, 0xb6, 0x08, 0xe8, 0xc5, 0xc1, 0xff, 0x1f, 0xa3, 0xf8,
	0xf2, 0x7a, 0xbe, 0xca, 0xe2, 0xc5, 0x2a, 0x8b, 0xff, 0xad, 0xb2, 0xf8, 0xfb, 0x3a, 0x8b, 0x16,
	0xeb, 0x2c, 0xfa, 0xb3, 0xce, 0xa2, 0x2f, 0x1f, 0x2a, 0x61, 0xf3, 0x8e, 0xdd, 0xe6, 0xfd, 0xae,
	0xb8, 0xa6, 0xe7, 0x02, 0x70, 0x4d, 0x28, 0x48, 0x41, 0x19, 0xfe, 0x16, 0xde, 0x89, 0x7d, 0x50,
	0xdc, 0xe0, 0x6e, 0x72, 0x3b, 0x70, 0x1b, 0xfb, 0xf4, 0x18, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xee,
	0xf3, 0x35, 0x45, 0x02, 0x00, 0x00,
}

func (this *Fund) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Fund)
	if !ok {
		that2, ok := that.(Fund)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TokenAddress != that1.TokenAddress {
		return false
	}
	if !this.Amount.Equal(that1.Amount) {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ConsensusAppAddress) > 0 {
		i -= len(m.ConsensusAppAddress)
		copy(dAtA[i:], m.ConsensusAppAddress)
		i = encodeVarintNitro(dAtA, i, uint64(len(m.ConsensusAppAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.VirtualPaymentAppAddress) > 0 {
		i -= len(m.VirtualPaymentAppAddress)
		copy(dAtA[i:], m.VirtualPaymentAppAddress)
		i = encodeVarintNitro(dAtA, i, uint64(len(m.VirtualPaymentAppAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.NitroAdjudicatorAddress) > 0 {
		i -= len(m.NitroAdjudicatorAddress)
		copy(dAtA[i:], m.NitroAdjudicatorAddress)
		i = encodeVarintNitro(dAtA, i, uint64(len(m.NitroAdjudicatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PaymentChannel) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PaymentChannel) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PaymentChannel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintNitro(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Fund) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Fund) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Fund) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintNitro(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.TokenAddress) > 0 {
		i -= len(m.TokenAddress)
		copy(dAtA[i:], m.TokenAddress)
		i = encodeVarintNitro(dAtA, i, uint64(len(m.TokenAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintNitro(dAtA []byte, offset int, v uint64) int {
	offset -= sovNitro(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NitroAdjudicatorAddress)
	if l > 0 {
		n += 1 + l + sovNitro(uint64(l))
	}
	l = len(m.VirtualPaymentAppAddress)
	if l > 0 {
		n += 1 + l + sovNitro(uint64(l))
	}
	l = len(m.ConsensusAppAddress)
	if l > 0 {
		n += 1 + l + sovNitro(uint64(l))
	}
	return n
}

func (m *PaymentChannel) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovNitro(uint64(l))
	}
	return n
}

func (m *Fund) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TokenAddress)
	if l > 0 {
		n += 1 + l + sovNitro(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovNitro(uint64(l))
	return n
}

func sovNitro(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNitro(x uint64) (n int) {
	return sovNitro(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNitro
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NitroAdjudicatorAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNitro
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthNitro
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthNitro
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NitroAdjudicatorAddress = append(m.NitroAdjudicatorAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.NitroAdjudicatorAddress == nil {
				m.NitroAdjudicatorAddress = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VirtualPaymentAppAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNitro
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthNitro
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthNitro
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VirtualPaymentAppAddress = append(m.VirtualPaymentAppAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.VirtualPaymentAppAddress == nil {
				m.VirtualPaymentAppAddress = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusAppAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNitro
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthNitro
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthNitro
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsensusAppAddress = append(m.ConsensusAppAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.ConsensusAppAddress == nil {
				m.ConsensusAppAddress = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNitro(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNitro
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PaymentChannel) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNitro
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PaymentChannel: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PaymentChannel: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNitro
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNitro
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNitro
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNitro(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNitro
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Fund) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNitro
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Fund: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Fund: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNitro
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNitro
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNitro
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNitro
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNitro
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNitro
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNitro(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNitro
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNitro(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNitro
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNitro
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNitro
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNitro
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNitro
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNitro
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNitro        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNitro          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNitro = fmt.Errorf("proto: unexpected end of group")
)
