// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cerc/nitro/v1/tx.proto

package v1

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgOpenChannel struct {
	// Nitro address of proposing party
	NitroAddress string `protobuf:"bytes,1,opt,name=nitro_address,json=nitroAddress,proto3" json:"nitro_address,omitempty"`
	// Nitro address of counterparty
	Counterparty string `protobuf:"bytes,2,opt,name=counterparty,proto3" json:"counterparty,omitempty"`
	// Simplified outcome just includes the funding amount from payer
	// TODO: review use of coins to represent ETH/ERC20
	Funds github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=funds,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"funds"`
	// Nitro channel ID
	ChannelId string `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// Tx signer address is independent of proposer ETH address
	Signer string `protobuf:"bytes,5,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgOpenChannel) Reset()         { *m = MsgOpenChannel{} }
func (m *MsgOpenChannel) String() string { return proto.CompactTextString(m) }
func (*MsgOpenChannel) ProtoMessage()    {}
func (*MsgOpenChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7ef3b32bf46dfb1, []int{0}
}
func (m *MsgOpenChannel) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgOpenChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgOpenChannel.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgOpenChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgOpenChannel.Merge(m, src)
}
func (m *MsgOpenChannel) XXX_Size() int {
	return m.Size()
}
func (m *MsgOpenChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgOpenChannel.DiscardUnknown(m)
}

var xxx_messageInfo_MsgOpenChannel proto.InternalMessageInfo

func (m *MsgOpenChannel) GetNitroAddress() string {
	if m != nil {
		return m.NitroAddress
	}
	return ""
}

func (m *MsgOpenChannel) GetCounterparty() string {
	if m != nil {
		return m.Counterparty
	}
	return ""
}

func (m *MsgOpenChannel) GetFunds() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Funds
	}
	return nil
}

func (m *MsgOpenChannel) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *MsgOpenChannel) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

type MsgOpenChannelResponse struct {
}

func (m *MsgOpenChannelResponse) Reset()         { *m = MsgOpenChannelResponse{} }
func (m *MsgOpenChannelResponse) String() string { return proto.CompactTextString(m) }
func (*MsgOpenChannelResponse) ProtoMessage()    {}
func (*MsgOpenChannelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7ef3b32bf46dfb1, []int{1}
}
func (m *MsgOpenChannelResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgOpenChannelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgOpenChannelResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgOpenChannelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgOpenChannelResponse.Merge(m, src)
}
func (m *MsgOpenChannelResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgOpenChannelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgOpenChannelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgOpenChannelResponse proto.InternalMessageInfo

type MsgCloseChannel struct {
	// Nitro channel ID to close
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// Whether to close via challenge (dispute resolution) or cooperative closure
	IsChallenge bool `protobuf:"varint,2,opt,name=is_challenge,json=isChallenge,proto3" json:"is_challenge,omitempty"`
	// Laconic address of proposing party
	Signer string `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgCloseChannel) Reset()         { *m = MsgCloseChannel{} }
func (m *MsgCloseChannel) String() string { return proto.CompactTextString(m) }
func (*MsgCloseChannel) ProtoMessage()    {}
func (*MsgCloseChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7ef3b32bf46dfb1, []int{2}
}
func (m *MsgCloseChannel) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCloseChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCloseChannel.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCloseChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCloseChannel.Merge(m, src)
}
func (m *MsgCloseChannel) XXX_Size() int {
	return m.Size()
}
func (m *MsgCloseChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCloseChannel.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCloseChannel proto.InternalMessageInfo

func (m *MsgCloseChannel) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *MsgCloseChannel) GetIsChallenge() bool {
	if m != nil {
		return m.IsChallenge
	}
	return false
}

func (m *MsgCloseChannel) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

type MsgCloseChannelResponse struct {
}

func (m *MsgCloseChannelResponse) Reset()         { *m = MsgCloseChannelResponse{} }
func (m *MsgCloseChannelResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCloseChannelResponse) ProtoMessage()    {}
func (*MsgCloseChannelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7ef3b32bf46dfb1, []int{3}
}
func (m *MsgCloseChannelResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCloseChannelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCloseChannelResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCloseChannelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCloseChannelResponse.Merge(m, src)
}
func (m *MsgCloseChannelResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCloseChannelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCloseChannelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCloseChannelResponse proto.InternalMessageInfo

type MsgCreatePaymentChannel struct {
	// Nitro address of proposing party
	NitroAddress string `protobuf:"bytes,1,opt,name=nitro_address,json=nitroAddress,proto3" json:"nitro_address,omitempty"`
	// Nitro address of counterparty
	Counterparty string `protobuf:"bytes,2,opt,name=counterparty,proto3" json:"counterparty,omitempty"`
	// Nitro addresses of intermediaries
	Intermediaries []string `protobuf:"bytes,3,rep,name=intermediaries,proto3" json:"intermediaries,omitempty"`
	// Challenge duration for the channel
	ChallengeDuration uint32 `protobuf:"varint,4,opt,name=challenge_duration,json=challengeDuration,proto3" json:"challenge_duration,omitempty"`
	// Funding amount for the payment channel
	Funds github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,5,rep,name=funds,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"funds"`
	// Nitro channel ID
	ChannelId string `protobuf:"bytes,6,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// Laconic address of proposing party
	Signer string `protobuf:"bytes,7,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgCreatePaymentChannel) Reset()         { *m = MsgCreatePaymentChannel{} }
func (m *MsgCreatePaymentChannel) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePaymentChannel) ProtoMessage()    {}
func (*MsgCreatePaymentChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7ef3b32bf46dfb1, []int{4}
}
func (m *MsgCreatePaymentChannel) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePaymentChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePaymentChannel.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePaymentChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePaymentChannel.Merge(m, src)
}
func (m *MsgCreatePaymentChannel) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePaymentChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePaymentChannel.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePaymentChannel proto.InternalMessageInfo

func (m *MsgCreatePaymentChannel) GetNitroAddress() string {
	if m != nil {
		return m.NitroAddress
	}
	return ""
}

func (m *MsgCreatePaymentChannel) GetCounterparty() string {
	if m != nil {
		return m.Counterparty
	}
	return ""
}

func (m *MsgCreatePaymentChannel) GetIntermediaries() []string {
	if m != nil {
		return m.Intermediaries
	}
	return nil
}

func (m *MsgCreatePaymentChannel) GetChallengeDuration() uint32 {
	if m != nil {
		return m.ChallengeDuration
	}
	return 0
}

func (m *MsgCreatePaymentChannel) GetFunds() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Funds
	}
	return nil
}

func (m *MsgCreatePaymentChannel) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *MsgCreatePaymentChannel) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

type MsgCreatePaymentChannelResponse struct {
}

func (m *MsgCreatePaymentChannelResponse) Reset()         { *m = MsgCreatePaymentChannelResponse{} }
func (m *MsgCreatePaymentChannelResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePaymentChannelResponse) ProtoMessage()    {}
func (*MsgCreatePaymentChannelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7ef3b32bf46dfb1, []int{5}
}
func (m *MsgCreatePaymentChannelResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePaymentChannelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePaymentChannelResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePaymentChannelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePaymentChannelResponse.Merge(m, src)
}
func (m *MsgCreatePaymentChannelResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePaymentChannelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePaymentChannelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePaymentChannelResponse proto.InternalMessageInfo

type MsgClosePaymentChannel struct {
	// Nitro channel ID to close
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// Laconic address of proposing party
	Signer string `protobuf:"bytes,2,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgClosePaymentChannel) Reset()         { *m = MsgClosePaymentChannel{} }
func (m *MsgClosePaymentChannel) String() string { return proto.CompactTextString(m) }
func (*MsgClosePaymentChannel) ProtoMessage()    {}
func (*MsgClosePaymentChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7ef3b32bf46dfb1, []int{6}
}
func (m *MsgClosePaymentChannel) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClosePaymentChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClosePaymentChannel.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClosePaymentChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClosePaymentChannel.Merge(m, src)
}
func (m *MsgClosePaymentChannel) XXX_Size() int {
	return m.Size()
}
func (m *MsgClosePaymentChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClosePaymentChannel.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClosePaymentChannel proto.InternalMessageInfo

func (m *MsgClosePaymentChannel) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *MsgClosePaymentChannel) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

type MsgClosePaymentChannelResponse struct {
}

func (m *MsgClosePaymentChannelResponse) Reset()         { *m = MsgClosePaymentChannelResponse{} }
func (m *MsgClosePaymentChannelResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClosePaymentChannelResponse) ProtoMessage()    {}
func (*MsgClosePaymentChannelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7ef3b32bf46dfb1, []int{7}
}
func (m *MsgClosePaymentChannelResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClosePaymentChannelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClosePaymentChannelResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClosePaymentChannelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClosePaymentChannelResponse.Merge(m, src)
}
func (m *MsgClosePaymentChannelResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClosePaymentChannelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClosePaymentChannelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClosePaymentChannelResponse proto.InternalMessageInfo

type MsgPay struct {
	// Nitro channel ID through which to send payment
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// Amount to pay
	Amount types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount"`
	// Laconic address of the payer
	Signer string `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgPay) Reset()         { *m = MsgPay{} }
func (m *MsgPay) String() string { return proto.CompactTextString(m) }
func (*MsgPay) ProtoMessage()    {}
func (*MsgPay) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7ef3b32bf46dfb1, []int{8}
}
func (m *MsgPay) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPay.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPay.Merge(m, src)
}
func (m *MsgPay) XXX_Size() int {
	return m.Size()
}
func (m *MsgPay) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPay.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPay proto.InternalMessageInfo

func (m *MsgPay) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *MsgPay) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *MsgPay) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

type MsgPayResponse struct {
}

func (m *MsgPayResponse) Reset()         { *m = MsgPayResponse{} }
func (m *MsgPayResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPayResponse) ProtoMessage()    {}
func (*MsgPayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7ef3b32bf46dfb1, []int{9}
}
func (m *MsgPayResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPayResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPayResponse.Merge(m, src)
}
func (m *MsgPayResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgPayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPayResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgOpenChannel)(nil), "cerc.nitro.v1.MsgOpenChannel")
	proto.RegisterType((*MsgOpenChannelResponse)(nil), "cerc.nitro.v1.MsgOpenChannelResponse")
	proto.RegisterType((*MsgCloseChannel)(nil), "cerc.nitro.v1.MsgCloseChannel")
	proto.RegisterType((*MsgCloseChannelResponse)(nil), "cerc.nitro.v1.MsgCloseChannelResponse")
	proto.RegisterType((*MsgCreatePaymentChannel)(nil), "cerc.nitro.v1.MsgCreatePaymentChannel")
	proto.RegisterType((*MsgCreatePaymentChannelResponse)(nil), "cerc.nitro.v1.MsgCreatePaymentChannelResponse")
	proto.RegisterType((*MsgClosePaymentChannel)(nil), "cerc.nitro.v1.MsgClosePaymentChannel")
	proto.RegisterType((*MsgClosePaymentChannelResponse)(nil), "cerc.nitro.v1.MsgClosePaymentChannelResponse")
	proto.RegisterType((*MsgPay)(nil), "cerc.nitro.v1.MsgPay")
	proto.RegisterType((*MsgPayResponse)(nil), "cerc.nitro.v1.MsgPayResponse")
}

func init() { proto.RegisterFile("cerc/nitro/v1/tx.proto", fileDescriptor_b7ef3b32bf46dfb1) }

var fileDescriptor_b7ef3b32bf46dfb1 = []byte{
	// 753 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x95, 0x4f, 0x4f, 0x13, 0x4f,
	0x18, 0xc7, 0xbb, 0x2d, 0xed, 0xef, 0xc7, 0xb4, 0xa0, 0xae, 0x08, 0x65, 0xa5, 0x0b, 0x2c, 0x7f,
	0x24, 0x84, 0xee, 0x5a, 0x3c, 0x98, 0x78, 0x93, 0x1a, 0x13, 0x0f, 0x8d, 0x4d, 0x2f, 0x26, 0xc6,
	0xa4, 0x99, 0xee, 0x8e, 0xc3, 0xc4, 0x76, 0x66, 0xb3, 0x33, 0x6d, 0xda, 0xc4, 0x03, 0x21, 0xf1,
	0x6e, 0xe2, 0x89, 0x83, 0x6f, 0xc0, 0x13, 0x2f, 0x83, 0x23, 0x89, 0x17, 0x4f, 0x4a, 0xc0, 0x84,
	0xb7, 0x61, 0x76, 0x76, 0x59, 0xda, 0x65, 0x0b, 0x1c, 0x8c, 0xa7, 0x76, 0x9e, 0xe7, 0x99, 0xf9,
	0x7e, 0xe6, 0x79, 0x9e, 0x79, 0x16, 0xcc, 0xda, 0xc8, 0xb3, 0x2d, 0x4a, 0x84, 0xc7, 0xac, 0x5e,
	0xc5, 0x12, 0x7d, 0xd3, 0xf5, 0x98, 0x60, 0xea, 0x94, 0x6f, 0x37, 0xa5, 0xdd, 0xec, 0x55, 0xb4,
	0x05, 0xcc, 0x18, 0x6e, 0x23, 0x0b, 0xba, 0xc4, 0x82, 0x94, 0x32, 0x01, 0x05, 0x61, 0x94, 0x07,
	0xc1, 0xda, 0x0c, 0x66, 0x98, 0xc9, 0xbf, 0x96, 0xff, 0x2f, 0xb4, 0xea, 0x36, 0xe3, 0x1d, 0xc6,
	0xad, 0x16, 0xe4, 0xc8, 0xea, 0x55, 0x5a, 0x48, 0xc0, 0x8a, 0x65, 0x33, 0x42, 0x43, 0xff, 0x5c,
	0xe8, 0xef, 0x70, 0xec, 0x4b, 0x77, 0x38, 0x0e, 0x1c, 0xc6, 0x5e, 0x1a, 0x4c, 0xd7, 0x38, 0x7e,
	0xed, 0x22, 0x5a, 0xdd, 0x85, 0x94, 0xa2, 0xb6, 0xba, 0x02, 0xa6, 0x24, 0x4b, 0x13, 0x3a, 0x8e,
	0x87, 0x38, 0x2f, 0x2a, 0x4b, 0xca, 0xc6, 0x64, 0xa3, 0x20, 0x8d, 0xcf, 0x03, 0x9b, 0x6a, 0x80,
	0x82, 0xcd, 0xba, 0x54, 0x20, 0xcf, 0x85, 0x9e, 0x18, 0x14, 0xd3, 0x41, 0xcc, 0xb0, 0x4d, 0x85,
	0x20, 0xfb, 0xbe, 0x4b, 0x1d, 0x5e, 0xcc, 0x2c, 0x65, 0x36, 0xf2, 0xdb, 0xf3, 0x66, 0x00, 0x61,
	0xfa, 0x90, 0x66, 0x08, 0x69, 0x56, 0x19, 0xa1, 0x3b, 0x8f, 0x8f, 0x7e, 0x2e, 0xa6, 0xbe, 0xfd,
	0x5a, 0xdc, 0xc0, 0x44, 0xec, 0x76, 0x5b, 0xa6, 0xcd, 0x3a, 0x56, 0x48, 0x1c, 0xfc, 0x94, 0xb9,
	0xf3, 0xc1, 0x12, 0x03, 0x17, 0x71, 0xb9, 0x81, 0x37, 0x82, 0x93, 0xd5, 0x12, 0x00, 0x76, 0x80,
	0xdd, 0x24, 0x4e, 0x71, 0x42, 0x42, 0x4c, 0x86, 0x96, 0x57, 0x8e, 0x3a, 0x0b, 0x72, 0x9c, 0x60,
	0x8a, 0xbc, 0x62, 0x56, 0xba, 0xc2, 0xd5, 0xb3, 0xfc, 0xfe, 0xf9, 0xe1, 0x66, 0xb8, 0x30, 0x8a,
	0x60, 0x76, 0x34, 0x03, 0x0d, 0xc4, 0x5d, 0x46, 0x39, 0x32, 0xfa, 0xe0, 0x4e, 0x8d, 0xe3, 0x6a,
	0x9b, 0x71, 0x74, 0x91, 0x9c, 0x51, 0x41, 0x25, 0x2e, 0xb8, 0x0c, 0x0a, 0x84, 0x37, 0xed, 0x5d,
	0xd8, 0x6e, 0x23, 0x8a, 0x91, 0x4c, 0xcb, 0xff, 0x8d, 0x3c, 0xe1, 0xd5, 0x0b, 0xd3, 0x10, 0x53,
	0x66, 0x3c, 0xd3, 0x3c, 0x98, 0x8b, 0x29, 0x47, 0x50, 0x27, 0xe9, 0xc0, 0xe7, 0x21, 0x28, 0x50,
	0x1d, 0x0e, 0x3a, 0x88, 0x8a, 0xbf, 0x5e, 0xba, 0x75, 0x30, 0x4d, 0xfc, 0x55, 0x07, 0x39, 0x04,
	0x7a, 0x04, 0x05, 0x35, 0x9c, 0x6c, 0xc4, 0xac, 0x6a, 0x19, 0xa8, 0xd1, 0x65, 0x9b, 0x4e, 0xd7,
	0x93, 0xad, 0x2a, 0xeb, 0x30, 0xd5, 0xb8, 0x17, 0x79, 0x5e, 0x84, 0x8e, 0xcb, 0x8e, 0xc8, 0xfe,
	0xa3, 0x8e, 0xc8, 0x8d, 0xef, 0x88, 0xff, 0xc6, 0x67, 0x7f, 0x19, 0x2c, 0x8e, 0xc9, 0x70, 0x54,
	0x85, 0x77, 0xb2, 0x69, 0x64, 0x81, 0x62, 0x35, 0xb8, 0xa1, 0x43, 0x2e, 0x01, 0xd2, 0xe3, 0x01,
	0x96, 0x80, 0x9e, 0x7c, 0x7a, 0xa4, 0xff, 0x49, 0x01, 0xb9, 0x1a, 0xc7, 0x75, 0x38, 0xb8, 0x49,
	0xf0, 0x29, 0xc8, 0xc1, 0x8e, 0x5f, 0x5b, 0x29, 0x78, 0x6d, 0xd2, 0x27, 0xfc, 0xa4, 0x37, 0xc2,
	0xf0, 0xdb, 0x35, 0xea, 0x5d, 0x39, 0x3e, 0xea, 0x70, 0x70, 0x41, 0xb6, 0x7d, 0x90, 0x05, 0x99,
	0x1a, 0xc7, 0x6a, 0x1f, 0xe4, 0x87, 0xa7, 0x4a, 0xc9, 0x1c, 0x99, 0x72, 0xe6, 0xe8, 0x93, 0xd3,
	0xd6, 0xae, 0x75, 0x47, 0xd7, 0x5e, 0xd9, 0xff, 0xfe, 0xfb, 0x4b, 0xba, 0x64, 0x3c, 0xb4, 0x46,
	0x67, 0x29, 0x73, 0x11, 0x6d, 0x86, 0x77, 0x56, 0x3f, 0x82, 0xc2, 0xc8, 0x9b, 0xd5, 0xaf, 0x9e,
	0x3d, 0xec, 0xd7, 0xd6, 0xaf, 0xf7, 0x47, 0xe2, 0xab, 0x52, 0x5c, 0x37, 0x16, 0x62, 0xe2, 0xb6,
	0x1f, 0x1c, 0xa9, 0x7f, 0x55, 0xc0, 0x4c, 0xe2, 0xe3, 0x4c, 0x92, 0x49, 0x88, 0xd3, 0xcc, 0xdb,
	0xc5, 0x45, 0x58, 0x65, 0x89, 0xf5, 0xc8, 0x58, 0x8b, 0x63, 0xc9, 0x4d, 0x4d, 0x37, 0xd8, 0x15,
	0xf1, 0x1d, 0x28, 0xe0, 0x7e, 0x52, 0xdf, 0xae, 0x8d, 0xc9, 0x42, 0x8c, 0xae, 0x7c, 0xab, 0xb0,
	0x08, 0x6e, 0x4b, 0xc2, 0xad, 0x1b, 0xab, 0x89, 0x39, 0x8b, 0xb3, 0xbd, 0x01, 0x19, 0xbf, 0xa3,
	0x1f, 0x5c, 0xd5, 0xa8, 0xc3, 0x81, 0x56, 0x4a, 0x34, 0x47, 0x52, 0x9a, 0x94, 0x9a, 0x31, 0xd4,
	0x98, 0x94, 0x0b, 0x07, 0x5a, 0x76, 0xef, 0xfc, 0x70, 0x53, 0xd9, 0x79, 0x79, 0x74, 0xaa, 0x2b,
	0xc7, 0xa7, 0xba, 0x72, 0x72, 0xaa, 0x2b, 0x9f, 0xcf, 0xf4, 0xd4, 0xf1, 0x99, 0x9e, 0xfa, 0x71,
	0xa6, 0xa7, 0xde, 0x6e, 0x61, 0x22, 0xcc, 0x9e, 0xd3, 0x32, 0x05, 0x93, 0xdb, 0xcb, 0x84, 0x59,
	0x6d, 0x68, 0x33, 0x4a, 0x6c, 0xc7, 0xea, 0x87, 0x87, 0xc9, 0x71, 0xe3, 0x7f, 0x5e, 0x73, 0xf2,
	0xe3, 0xf9, 0xe4, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xae, 0xc4, 0xed, 0x93, 0xd2, 0x07, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// TODO: OpenLedgerChannel?
	OpenChannel(ctx context.Context, in *MsgOpenChannel, opts ...grpc.CallOption) (*MsgOpenChannelResponse, error)
	CloseChannel(ctx context.Context, in *MsgCloseChannel, opts ...grpc.CallOption) (*MsgCloseChannelResponse, error)
	CreatePaymentChannel(ctx context.Context, in *MsgCreatePaymentChannel, opts ...grpc.CallOption) (*MsgCreatePaymentChannelResponse, error)
	ClosePaymentChannel(ctx context.Context, in *MsgClosePaymentChannel, opts ...grpc.CallOption) (*MsgClosePaymentChannelResponse, error)
	Pay(ctx context.Context, in *MsgPay, opts ...grpc.CallOption) (*MsgPayResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) OpenChannel(ctx context.Context, in *MsgOpenChannel, opts ...grpc.CallOption) (*MsgOpenChannelResponse, error) {
	out := new(MsgOpenChannelResponse)
	err := c.cc.Invoke(ctx, "/cerc.nitro.v1.Msg/OpenChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CloseChannel(ctx context.Context, in *MsgCloseChannel, opts ...grpc.CallOption) (*MsgCloseChannelResponse, error) {
	out := new(MsgCloseChannelResponse)
	err := c.cc.Invoke(ctx, "/cerc.nitro.v1.Msg/CloseChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreatePaymentChannel(ctx context.Context, in *MsgCreatePaymentChannel, opts ...grpc.CallOption) (*MsgCreatePaymentChannelResponse, error) {
	out := new(MsgCreatePaymentChannelResponse)
	err := c.cc.Invoke(ctx, "/cerc.nitro.v1.Msg/CreatePaymentChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClosePaymentChannel(ctx context.Context, in *MsgClosePaymentChannel, opts ...grpc.CallOption) (*MsgClosePaymentChannelResponse, error) {
	out := new(MsgClosePaymentChannelResponse)
	err := c.cc.Invoke(ctx, "/cerc.nitro.v1.Msg/ClosePaymentChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Pay(ctx context.Context, in *MsgPay, opts ...grpc.CallOption) (*MsgPayResponse, error) {
	out := new(MsgPayResponse)
	err := c.cc.Invoke(ctx, "/cerc.nitro.v1.Msg/Pay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// TODO: OpenLedgerChannel?
	OpenChannel(context.Context, *MsgOpenChannel) (*MsgOpenChannelResponse, error)
	CloseChannel(context.Context, *MsgCloseChannel) (*MsgCloseChannelResponse, error)
	CreatePaymentChannel(context.Context, *MsgCreatePaymentChannel) (*MsgCreatePaymentChannelResponse, error)
	ClosePaymentChannel(context.Context, *MsgClosePaymentChannel) (*MsgClosePaymentChannelResponse, error)
	Pay(context.Context, *MsgPay) (*MsgPayResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) OpenChannel(ctx context.Context, req *MsgOpenChannel) (*MsgOpenChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenChannel not implemented")
}
func (*UnimplementedMsgServer) CloseChannel(ctx context.Context, req *MsgCloseChannel) (*MsgCloseChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseChannel not implemented")
}
func (*UnimplementedMsgServer) CreatePaymentChannel(ctx context.Context, req *MsgCreatePaymentChannel) (*MsgCreatePaymentChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePaymentChannel not implemented")
}
func (*UnimplementedMsgServer) ClosePaymentChannel(ctx context.Context, req *MsgClosePaymentChannel) (*MsgClosePaymentChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClosePaymentChannel not implemented")
}
func (*UnimplementedMsgServer) Pay(ctx context.Context, req *MsgPay) (*MsgPayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pay not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_OpenChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgOpenChannel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).OpenChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerc.nitro.v1.Msg/OpenChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).OpenChannel(ctx, req.(*MsgOpenChannel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CloseChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCloseChannel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CloseChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerc.nitro.v1.Msg/CloseChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CloseChannel(ctx, req.(*MsgCloseChannel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreatePaymentChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreatePaymentChannel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreatePaymentChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerc.nitro.v1.Msg/CreatePaymentChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreatePaymentChannel(ctx, req.(*MsgCreatePaymentChannel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClosePaymentChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClosePaymentChannel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClosePaymentChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerc.nitro.v1.Msg/ClosePaymentChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClosePaymentChannel(ctx, req.(*MsgClosePaymentChannel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Pay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPay)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Pay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerc.nitro.v1.Msg/Pay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Pay(ctx, req.(*MsgPay))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cerc.nitro.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenChannel",
			Handler:    _Msg_OpenChannel_Handler,
		},
		{
			MethodName: "CloseChannel",
			Handler:    _Msg_CloseChannel_Handler,
		},
		{
			MethodName: "CreatePaymentChannel",
			Handler:    _Msg_CreatePaymentChannel_Handler,
		},
		{
			MethodName: "ClosePaymentChannel",
			Handler:    _Msg_ClosePaymentChannel_Handler,
		},
		{
			MethodName: "Pay",
			Handler:    _Msg_Pay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cerc/nitro/v1/tx.proto",
}

func (m *MsgOpenChannel) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgOpenChannel) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgOpenChannel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Funds) > 0 {
		for iNdEx := len(m.Funds) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Funds[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Counterparty) > 0 {
		i -= len(m.Counterparty)
		copy(dAtA[i:], m.Counterparty)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Counterparty)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.NitroAddress) > 0 {
		i -= len(m.NitroAddress)
		copy(dAtA[i:], m.NitroAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NitroAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgOpenChannelResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgOpenChannelResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgOpenChannelResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCloseChannel) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCloseChannel) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCloseChannel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x1a
	}
	if m.IsChallenge {
		i--
		if m.IsChallenge {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCloseChannelResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCloseChannelResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCloseChannelResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreatePaymentChannel) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePaymentChannel) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePaymentChannel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Funds) > 0 {
		for iNdEx := len(m.Funds) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Funds[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.ChallengeDuration != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ChallengeDuration))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Intermediaries) > 0 {
		for iNdEx := len(m.Intermediaries) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Intermediaries[iNdEx])
			copy(dAtA[i:], m.Intermediaries[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Intermediaries[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Counterparty) > 0 {
		i -= len(m.Counterparty)
		copy(dAtA[i:], m.Counterparty)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Counterparty)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.NitroAddress) > 0 {
		i -= len(m.NitroAddress)
		copy(dAtA[i:], m.NitroAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NitroAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreatePaymentChannelResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePaymentChannelResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePaymentChannelResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgClosePaymentChannel) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClosePaymentChannel) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClosePaymentChannel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClosePaymentChannelResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClosePaymentChannelResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClosePaymentChannelResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgPay) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPay) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPay) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgPayResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPayResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPayResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgOpenChannel) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NitroAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Counterparty)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Funds) > 0 {
		for _, e := range m.Funds {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgOpenChannelResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCloseChannel) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.IsChallenge {
		n += 2
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCloseChannelResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreatePaymentChannel) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NitroAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Counterparty)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Intermediaries) > 0 {
		for _, s := range m.Intermediaries {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.ChallengeDuration != 0 {
		n += 1 + sovTx(uint64(m.ChallengeDuration))
	}
	if len(m.Funds) > 0 {
		for _, e := range m.Funds {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreatePaymentChannelResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgClosePaymentChannel) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClosePaymentChannelResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgPay) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgPayResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgOpenChannel) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgOpenChannel: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgOpenChannel: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NitroAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NitroAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Counterparty", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Counterparty = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Funds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Funds = append(m.Funds, types.Coin{})
			if err := m.Funds[len(m.Funds)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgOpenChannelResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgOpenChannelResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgOpenChannelResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCloseChannel) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCloseChannel: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCloseChannel: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsChallenge", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsChallenge = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCloseChannelResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCloseChannelResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCloseChannelResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreatePaymentChannel) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePaymentChannel: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePaymentChannel: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NitroAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NitroAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Counterparty", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Counterparty = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Intermediaries", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Intermediaries = append(m.Intermediaries, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengeDuration", wireType)
			}
			m.ChallengeDuration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChallengeDuration |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Funds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Funds = append(m.Funds, types.Coin{})
			if err := m.Funds[len(m.Funds)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreatePaymentChannelResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePaymentChannelResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePaymentChannelResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClosePaymentChannel) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClosePaymentChannel: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClosePaymentChannel: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClosePaymentChannelResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClosePaymentChannelResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClosePaymentChannelResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPay) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPay: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPay: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPayResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPayResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPayResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
